### ISSUE TITLE
Slash Command: /echo

### ISSUE THREAD

**Issue by StephanWells** [Raid-Training-Initiative/RTIBot#332]
**Details:**
* `/echo <message> [channel]` echoes the given `<message>`, optionally to the given `[channel]` (to the same channel if none specified).

**Current functionality:**
* `EchoCommand`

**Notes:**
* Ensure that there's validation on the `[channel]` parameter (i.e. it accepts only Discord channels).
* No autocomplete needed.
* Error messages should be ephemeral.

**Comment by Akhronox** [comment]
This is already done.

**Comment by StephanWells** [comment]
> This is already done.

Just made it for posterity. Can close the issue I suppose.
